name: Staged CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Run Composite Action to Install Packages
      uses: .github/actions

    - name: Run tests
      run: |
        poetry run pytest

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Run Composite Action to Install Packages
        uses: .github/actions
      - name: Run Pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files